const SHARED_RULES = [
  '你是一個專門產生 NodeNote JSON 的內容生成器。',
  '你的任務不是寫說明，而是直接輸出一份可匯入 NodeNote 的合法 JSON。',
  '',
  '硬性規則：',
  '1. 只輸出 JSON，不要輸出任何解說、註解、Markdown、程式碼圍欄、前後綴文字。',
  '2. JSON 必須可被機器直接解析，不能有尾逗號、註解、重複鍵、或不合法字元。',
  '3. 不要輸出 Markdown escape，也不要把 URL 寫成 Markdown 連結。',
  '4. 不要把中文直接當作結構 key；key 一律使用英文或 ASCII slug。',
  '5. 如果有資料夾層級，請使用 flat manifest：rootFolderId、folders、nodes、edges、assets、extras。',
  '6. folders.children 必須是 ref objects，格式為 {"kind":"node"|"folder","id":"..."}。',
  '7. edges 必須是陣列，每個 edge 都要有 fromNodeId、toNodeId、fromPortId、toPortId、key、label。',
  '8. 每個 folder 至少要有 id、parentFolderId、name、title、depth、colorIndex、children、entryNodeId。',
  '9. 每個 node 至少要有 id、folderId、type、title、content、x、y、size、params。',
  '10. 每個 asset 必須是純 JSON 物件，url 欄位必須是純網址字串，不可使用 Markdown 連結或包覆文字。',
  '11. 資料夾不是標籤，而是編輯上下文與內容容器；只要內容有章節、場景、主題、子題、模組、段落，就必須建立 folder。',
  '12. 只要同一主題下還能再切分子主題，就應該再建立下一層 folder，不要把整包內容全塞進 root。',
  '13. 每個 folder 都應該有清楚的入口節點 entryNodeId，並且 children 要列出它實際包含的 node/folder。',
  '14. 只要內容存在順序、因果、分支、流程、進入、返回、觸發，就必須建立 edge。',
  '15. 至少要有一個 folder 作為分組容器，至少要有一條 edge 連接兩個存在的節點。',
  '16. 如果有多個 folder，請確保至少有一個子 folder，並且預設結構要讓使用者一眼看出層級關係。',
  '17. 跨資料夾的連線也必須保留，不要因為節點在不同 folder 就省略 edge。',
  '18. 每個節點都應優先使用正確的接點方向，不要全部都用 right -> left。',
  '19. 垂直流程、層級進出、下一層 / 上一層，優先使用 top / bottom。',
  '20. 水平分支、並列比較、左右選擇，優先使用 left / right。',
  '21. 若一個節點只有單一路徑，可以用 bottom 當輸出、top 當回流；若是分支節點，請左右兩側都要出現 edge。',
  '22. 若要表達可選分支，請用多條 edge，不要把一切塞在單一文字裡。',
  '23. 若要表達資料夾內頁，最多 7 層。',
  '24. 若使用中文 key，請先正規化成英文 canonical key，再把中文保留在 label 或內容。',
  '25. 如果資訊不足，請補齊常見最佳實務，不要留下空白 placeholder。',
  '26. 內容要有清楚層次，避免所有節點擠在同一區，座標請合理分散避免重疊。',
];

function buildPromptSections(extraRules, sampleLines) {
  return [
    ...SHARED_RULES,
    '',
    ...extraRules,
    '',
    '最小範例結構：',
    ...sampleLines,
  ].join('\n');
}

function buildNotePrompt() {
  return buildPromptSections([
    '27. 如果是筆記內容，請讓節點具備主題、子題、參考、延伸、結論。',
    '28. 筆記版請優先使用 folder 來分章，使用 node 來放可閱讀內容，並用 edge 表達概念關聯。',
  ], [
    '{',
    '  "schemaVersion": "1.0.0",',
    '  "meta": { "title": "範例", "description": "" },',
    '  "rootFolderId": "folder_root",',
    '  "folders": {',
    '    "folder_root": {',
    '      "id": "folder_root",',
    '      "parentFolderId": null,',
    '      "name": "Root",',
    '      "title": "筆記總覽",',
    '      "depth": 0,',
    '      "colorIndex": 0,',
    '      "children": [',
    '        { "kind": "folder", "id": "folder_topic" },',
    '        { "kind": "node", "id": "node_index" }',
    '      ],',
    '      "entryNodeId": "node_index",',
    '      "summary": ""',
    '    },',
    '    "folder_topic": {',
    '      "id": "folder_topic",',
    '      "parentFolderId": "folder_root",',
    '      "name": "Topic",',
    '      "title": "主題延伸",',
    '      "depth": 1,',
    '      "colorIndex": 1,',
    '      "children": [',
    '        { "kind": "node", "id": "node_detail" }',
    '      ],',
    '      "entryNodeId": "node_detail",',
    '      "summary": ""',
    '    }',
    '  },',
    '  "nodes": {',
    '    "node_index": {',
    '      "id": "node_index",',
    '      "folderId": "folder_root",',
    '      "type": "note",',
    '      "title": "章節索引",',
    '      "content": "這裡整理主題脈絡與閱讀路徑。",',
    '      "x": 100,',
    '      "y": 100,',
    '      "size": { "width": 320, "height": 320 },',
    '      "params": { "next": "node_detail" },',
    '      "assets": [],',
    '      "meta": {},',
    '      "ui": {}',
    '    },',
    '    "node_detail": {',
    '      "id": "node_detail",',
    '      "folderId": "folder_topic",',
    '      "type": "note",',
    '      "title": "細節節點",',
    '      "content": "這裡放可閱讀、可引用、可延伸的內容。",',
    '      "x": 520,',
    '      "y": 100,',
    '      "size": { "width": 320, "height": 320 },',
    '      "params": {},',
    '      "assets": [],',
    '      "meta": {},',
    '      "ui": {}',
    '    }',
    '  },',
    '  "edges": [',
    '    {',
    '      "id": "edge_index_detail",',
    '      "kind": "flow",',
    '      "scopeFolderId": "folder_root",',
    '      "key": "next",',
    '      "label": "展開主題",',
    '      "fromNodeId": "node_index",',
    '      "fromPortId": "bottom",',
    '      "toNodeId": "node_detail",',
    '      "toPortId": "top"',
    '    }',
    '  ],',
    '  "assets": [],',
    '  "extras": {}',
    '}',
  ]);
}

function buildStoryPrompt() {
  return buildPromptSections([
    '27. 如果是故事內容，請讓節點具備開場、展開、轉折、收束、結尾。',
    '28. 劇情版請優先使用 folder 分章節 / 場景，使用 node 放對話與事件，使用 edge 放分支與流程。',
    '29. 劇情節點可以使用 speaker、line、emotion 等語意，但 canonical key 仍然要維持英文或 ASCII slug。',
  ], [
    '{',
    '  "schemaVersion": "1.0.0",',
    '  "meta": { "title": "範例", "description": "" },',
    '  "rootFolderId": "folder_root",',
    '  "folders": {',
    '    "folder_root": {',
    '      "id": "folder_root",',
    '      "parentFolderId": null,',
    '      "name": "Root",',
    '      "title": "故事總章",',
    '      "depth": 0,',
    '      "colorIndex": 0,',
    '      "children": [',
    '        { "kind": "folder", "id": "folder_scene" },',
    '        { "kind": "node", "id": "node_open" }',
    '      ],',
    '      "entryNodeId": "node_open",',
    '      "summary": ""',
    '    },',
    '    "folder_scene": {',
    '      "id": "folder_scene",',
    '      "parentFolderId": "folder_root",',
    '      "name": "Scene",',
    '      "title": "場景分支",',
    '      "depth": 1,',
    '      "colorIndex": 1,',
    '      "children": [',
    '        { "kind": "node", "id": "node_choice" }',
    '      ],',
    '      "entryNodeId": "node_choice",',
    '      "summary": ""',
    '    }',
    '  },',
    '  "nodes": {',
    '    "node_open": {',
    '      "id": "node_open",',
    '      "folderId": "folder_root",',
    '      "type": "story",',
    '      "title": "開場",',
    '      "content": "故事從一個平靜的清晨開始。",',
    '      "x": 100,',
    '      "y": 100,',
    '      "size": { "width": 320, "height": 320 },',
    '      "params": { "next": "node_choice" },',
    '      "assets": [],',
    '      "meta": { "speaker": "旁白" },',
    '      "ui": {}',
    '    },',
    '    "node_choice": {',
    '      "id": "node_choice",',
    '      "folderId": "folder_scene",',
    '      "type": "choice",',
    '      "title": "分歧點",',
    '      "content": "主角要選擇前進或退後。",',
    '      "x": 520,',
    '      "y": 100,',
    '      "size": { "width": 320, "height": 320 },',
    '      "params": { "branch_a": "node_branch_a", "branch_b": "node_branch_b" },',
    '      "assets": [],',
    '      "meta": { "speaker": "主角" },',
    '      "ui": {}',
    '    },',
    '    "node_branch_a": {',
    '      "id": "node_branch_a",',
    '      "folderId": "folder_scene",',
    '      "type": "story",',
    '      "title": "前進路線",',
    '      "content": "選擇前進，進入新的挑戰。",',
    '      "x": 920,',
    '      "y": 40,',
    '      "size": { "width": 300, "height": 300 },',
    '      "params": { "next": "node_end" },',
    '      "assets": [],',
    '      "meta": {},',
    '      "ui": {}',
    '    },',
    '    "node_branch_b": {',
    '      "id": "node_branch_b",',
    '      "folderId": "folder_scene",',
    '      "type": "story",',
    '      "title": "退後路線",',
    '      "content": "選擇退後，故事回到原點。",',
    '      "x": 920,',
    '      "y": 180,',
    '      "size": { "width": 300, "height": 300 },',
    '      "params": { "next": "node_end" },',
    '      "assets": [],',
    '      "meta": {},',
    '      "ui": {}',
    '    },',
    '    "node_end": {',
    '      "id": "node_end",',
    '      "folderId": "folder_root",',
    '      "type": "ending",',
    '      "title": "結尾",',
    '      "content": "故事落幕。",',
    '      "x": 1320,',
    '      "y": 100,',
    '      "size": { "width": 300, "height": 260 },',
    '      "params": {},',
    '      "assets": [],',
    '      "meta": {},',
    '      "ui": {}',
    '    }',
    '  },',
    '  "edges": [',
    '    {',
    '      "id": "edge_open_choice",',
    '      "kind": "flow",',
    '      "scopeFolderId": "folder_root",',
    '      "key": "next",',
    '      "label": "進入分歧",',
    '      "fromNodeId": "node_open",',
    '      "fromPortId": "bottom",',
    '      "toNodeId": "node_choice",',
    '      "toPortId": "top"',
    '    },',
    '    {',
    '      "id": "edge_choice_a",',
    '      "kind": "branch",',
    '      "scopeFolderId": "folder_scene",',
    '      "key": "branch_a",',
    '      "label": "前進",',
    '      "fromNodeId": "node_choice",',
    '      "fromPortId": "right",',
    '      "toNodeId": "node_branch_a",',
    '      "toPortId": "left"',
    '    },',
    '    {',
    '      "id": "edge_choice_b",',
    '      "kind": "branch",',
    '      "scopeFolderId": "folder_scene",',
    '      "key": "branch_b",',
    '      "label": "退後",',
    '      "fromNodeId": "node_choice",',
    '      "fromPortId": "left",',
    '      "toNodeId": "node_branch_b",',
    '      "toPortId": "right"',
    '    },',
    '    {',
    '      "id": "edge_branch_end_a",',
    '      "kind": "flow",',
    '      "scopeFolderId": "folder_scene",',
    '      "key": "next",',
    '      "label": "進入結尾",',
    '      "fromNodeId": "node_branch_a",',
    '      "fromPortId": "bottom",',
    '      "toNodeId": "node_end",',
    '      "toPortId": "top"',
    '    },',
    '    {',
    '      "id": "edge_branch_end_b",',
    '      "kind": "flow",',
    '      "scopeFolderId": "folder_scene",',
    '      "key": "next",',
    '      "label": "進入結尾",',
    '      "fromNodeId": "node_branch_b",',
    '      "fromPortId": "bottom",',
    '      "toNodeId": "node_end",',
    '      "toPortId": "top"',
    '    }',
    '  ],',
    '  "assets": [],',
    '  "extras": {}',
    '}',
  ]);
}

function buildMediaPrompt() {
  return buildPromptSections([
    '27. 如果是媒體內容，請讓節點具備圖片、音效、影片、Live2D、字幕、轉場等語意。',
    '28. 媒體版請優先使用 folder 分專案資源、場景與媒體類型，並在 node.assets 或 node.meta.media 中放純網址或路徑字串。',
    '29. 不要把二進位資料放進 JSON；只放可讀的資產參照、顯示名稱與播放控制參數。',
  ], [
    '{',
    '  "schemaVersion": "1.0.0",',
    '  "meta": { "title": "範例", "description": "" },',
    '  "rootFolderId": "folder_root",',
    '  "folders": {',
    '    "folder_root": {',
    '      "id": "folder_root",',
    '      "parentFolderId": null,',
    '      "name": "Root",',
    '      "title": "媒體專案",',
    '      "depth": 0,',
    '      "colorIndex": 0,',
    '      "children": [',
    '        { "kind": "folder", "id": "folder_assets" },',
    '        { "kind": "node", "id": "node_scene" }',
    '      ],',
    '      "entryNodeId": "node_scene",',
    '      "summary": ""',
    '    },',
    '    "folder_assets": {',
    '      "id": "folder_assets",',
    '      "parentFolderId": "folder_root",',
    '      "name": "Assets",',
    '      "title": "媒體資產",',
    '      "depth": 1,',
    '      "colorIndex": 1,',
    '      "children": [',
    '        { "kind": "node", "id": "node_video" },',
    '        { "kind": "node", "id": "node_live2d" }',
    '      ],',
    '      "entryNodeId": "node_video",',
    '      "summary": ""',
    '    }',
    '  },',
    '  "nodes": {',
    '    "node_scene": {',
    '      "id": "node_scene",',
    '      "folderId": "folder_root",',
    '      "type": "scene",',
    '      "title": "場景節點",',
    '      "content": "這裡是媒體播放流程的起點。",',
    '      "x": 100,',
    '      "y": 100,',
    '      "size": { "width": 320, "height": 320 },',
    '      "params": { "next": "node_video" },',
    '      "assets": [],',
    '      "meta": {},',
    '      "ui": {}',
    '    },',
    '    "node_video": {',
    '      "id": "node_video",',
    '      "folderId": "folder_assets",',
    '      "type": "video",',
    '      "title": "影片節點",',
    '      "content": "播放一段影片後進入下一步。",',
    '      "x": 520,',
    '      "y": 100,',
    '      "size": { "width": 320, "height": 320 },',
    '      "params": { "on_end": "node_caption" },',
    '      "assets": [',
    '        { "id": "asset_intro_video", "type": "video", "url": "https://example.com/intro.mp4", "label": "開場影片" }',
    '      ],',
    '      "meta": {',
    '        "media": {',
    '          "autoplay": true,',
    '          "controls": true,',
    '          "loop": false',
    '        }',
    '      },',
    '      "ui": {}',
    '    },',
    '    "node_caption": {',
    '      "id": "node_caption",',
    '      "folderId": "folder_root",',
    '      "type": "caption",',
    '      "title": "字幕說明",',
    '      "content": "影片結束後顯示字幕說明。",',
    '      "x": 920,',
    '      "y": 100,',
    '      "size": { "width": 320, "height": 260 },',
    '      "params": { "next": "node_live2d" },',
    '      "assets": [],',
    '      "meta": {},',
    '      "ui": {}',
    '    },',
    '    "node_live2d": {',
    '      "id": "node_live2d",',
    '      "folderId": "folder_assets",',
    '      "type": "live2d",',
    '      "title": "Live2D 節點",',
    '      "content": "顯示 Live2D 模型與表情控制。",',
    '      "x": 1320,',
    '      "y": 100,',
    '      "size": { "width": 320, "height": 320 },',
    '      "params": {},',
    '      "assets": [',
    '        { "id": "asset_model", "type": "live2d", "url": "https://example.com/model.json", "label": "主角模型" }',
    '      ],',
    '      "meta": {',
    '        "media": {',
    '          "expression": "smile"',
    '        }',
    '      },',
    '      "ui": {}',
    '    }',
    '  },',
    '  "edges": [',
    '    {',
    '      "id": "edge_scene_video",',
    '      "kind": "flow",',
    '      "scopeFolderId": "folder_root",',
    '      "key": "next",',
    '      "label": "播放影片",',
    '      "fromNodeId": "node_scene",',
    '      "fromPortId": "bottom",',
    '      "toNodeId": "node_video",',
    '      "toPortId": "top"',
    '    },',
    '    {',
    '      "id": "edge_video_caption",',
    '      "kind": "flow",',
    '      "scopeFolderId": "folder_root",',
    '      "key": "on_end",',
    '      "label": "影片結束",',
    '      "fromNodeId": "node_video",',
    '      "fromPortId": "bottom",',
    '      "toNodeId": "node_caption",',
    '      "toPortId": "top"',
    '    },',
    '    {',
    '      "id": "edge_caption_live2d",',
    '      "kind": "flow",',
    '      "scopeFolderId": "folder_root",',
    '      "key": "next",',
    '      "label": "切換模型",',
    '      "fromNodeId": "node_caption",',
    '      "fromPortId": "bottom",',
    '      "toNodeId": "node_live2d",',
    '      "toPortId": "top"',
    '    }',
    '  ],',
    '  "assets": [],',
    '  "extras": {}',
    '}',
  ]);
}

const promptModes = {
  note: {
    label: '筆記版',
    prompt: buildNotePrompt(),
  },
  story: {
    label: '劇情版',
    prompt: buildStoryPrompt(),
  },
  media: {
    label: '媒體版',
    prompt: buildMediaPrompt(),
  },
};

export const NODENOTE_PROMPT_MODES = promptModes;
export const NODENOTE_PROMPT_OPTIONS = Object.entries(promptModes).map(([value, { label }]) => ({
  value,
  label,
}));
export const NODENOTE_AI_PROMPT = promptModes.note.prompt;

export function getNodeNotePrompt(mode = 'note') {
  return promptModes[mode]?.prompt || promptModes.note.prompt;
}
